name: EPA Data Pipeline CI/CD

on:
  push:
    branches: 
      - main
      - test
  workflow_dispatch:    # Allows manual trigger from GitHub UI

env:
  AWS_REGION: us-east-1  # Change this to your AWS region
  ECR_REPOSITORY: epa-data-processor

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'PROD' || 'TEST' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          echo "Building for environment: ${ENVIRONMENT}"
          docker build \
            --build-arg SNOWFLAKE_USER=${SNOWFLAKE_USER} \
            --build-arg SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD} \
            --build-arg SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # Also tag as latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest-${ENVIRONMENT}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest-${ENVIRONMENT}

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster default \
            --service epa-processor-service \
            --force-new-deployment
            --task-definition epa-processor-task:3
